apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-zbxmvxfh
  janus-idp.io/tekton: go-zbxmvxfh
  backstage.io/kubernetes-id: go-zbxmvxfh
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-zbxmvxfh
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
